# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_rating', models.PositiveIntegerField()),
                ('product_category', models.ManyToManyField(to='ecommerce.Category')),
            ],
        ),
    ]
