# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(related_name='category', to='ecommerce.Category'),
        ),
    ]
