# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20171114_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_under_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(to='ecommerce.Category_under_Category'),
        ),
    ]
