# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20171114_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ecommerce.models._image_upload)),
                ('alt_text', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ecommerce.Product')),
            ],
        ),
    ]
