# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 20:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20171115_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
