# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20171115_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
