# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20171115_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category_under_Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category_under_category',
            name='category_name',
            field=models.CharField(default=' ', max_length=100, unique=True),
        ),
    ]
