# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_customerreview_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 12, 56, 44, 782065, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='customerreview',
            unique_together=set([('user', 'product')]),
        ),
    ]
