# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 20:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20171116_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 20, 56, 18, 923027, tzinfo=utc)),
        ),
    ]
