# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 22:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20171116_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField()),
                ('order_place_date', models.DateField(verbose_name=datetime.datetime(2017, 11, 15, 22, 43, 56, 223770, tzinfo=utc))),
                ('is_complete', models.BooleanField(default=False)),
                ('product_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 22, 43, 56, 219860, tzinfo=utc)),
        ),
    ]
