# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_auto_20171116_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='to_deliver',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 23, 14, 4, 564455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_place_date',
            field=models.DateField(verbose_name=datetime.datetime(2017, 11, 15, 23, 14, 4, 568189, tzinfo=utc)),
        ),
    ]
